/* Generated by Cython 0.29.37 */

#ifndef __PYX_HAVE__hmm_bw
#define __PYX_HAVE__hmm_bw

#include "Python.h"

#ifndef __PYX_HAVE_API__hmm_bw

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double D_min;
__PYX_EXTERN_C double D_max;
__PYX_EXTERN_C double unit_T;
__PYX_EXTERN_C double unit_L;

#endif /* !__PYX_HAVE_API__hmm_bw */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inithmm_bw(void);
#else
PyMODINIT_FUNC PyInit_hmm_bw(void);
#endif

#endif /* !__PYX_HAVE__hmm_bw */
